"""AEYE build orchestrator -- one command to produce the versioned installer.

    python build.py                 # build with the current version.txt
    python build.py --bump patch    # bump 1.0.0 -> 1.0.1 first, then build
    python build.py --bump minor    # ... 1.1.0
    python build.py --bump major    # ... 2.0.0
    python build.py --set 1.4.2     # set an explicit version, then build
    python build.py --no-installer  # freeze only (skip Inno Setup)
    python build.py --no-voice      # skip pre-fetching the default Piper voice

Pipeline:
  1. clean build/ and dist/
  2. resolve/bump the version (version.txt is the source of truth)
  3. record the build Python version (pybuild.txt) + generate the Win version
     resource + the installer's animated skull frames; fetch the WebView2
     bootstrapper and (optionally) pre-fetch the default Piper voice
  4. run PyInstaller (aeye.spec) -> dist/AEYE/
  5. run Inno Setup (installer/aeye.iss) -> dist/aeye-setup-vX.Y.Z.exe

Run this with the SAME Python you want the app frozen against; the extras
sidecar venv is later built to match (pybuild.txt), keeping the ABI aligned.
"""
import argparse
import os
import shutil
import subprocess
import sys
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(ROOT, "assets")
BUILD = os.path.join(ROOT, "build")
DIST = os.path.join(ROOT, "dist")

WEBVIEW2_URL = "https://go.microsoft.com/fwlink/p/?LinkId=2124703"
WEBVIEW2_EXE = os.path.join(ASSETS, "MicrosoftEdgeWebview2Setup.exe")

PIPER_REPO = "rhasspy/piper-voices"
DEFAULT_VOICE_KEY = "en_US-danny-low"
DEFAULT_VOICE_DIR = "en/en_US/danny/low"


# --------------------------------------------------------------------------
def log(msg: str) -> None:
    print(f"\n=== {msg} ===", flush=True)


def run(cmd: list, **kw) -> None:
    print("  $ " + " ".join(str(c) for c in cmd), flush=True)
    subprocess.run(cmd, check=True, **kw)


# --- version ---------------------------------------------------------------
def read_version() -> str:
    with open(os.path.join(ROOT, "version.txt"), encoding="utf-8") as f:
        return f.read().strip()


def write_version(v: str) -> None:
    with open(os.path.join(ROOT, "version.txt"), "w", encoding="utf-8") as f:
        f.write(v + "\n")


def bump(v: str, part: str) -> str:
    a, b, c = (int(x) for x in v.split("."))
    if part == "major":
        a, b, c = a + 1, 0, 0
    elif part == "minor":
        b, c = b + 1, 0
    else:
        c += 1
    return f"{a}.{b}.{c}"


# --- generated build inputs ------------------------------------------------
def write_pybuild() -> str:
    ver = f"{sys.version_info.major}.{sys.version_info.minor}"
    with open(os.path.join(ROOT, "pybuild.txt"), "w", encoding="utf-8") as f:
        f.write(ver + "\n")
    return ver


def write_version_info(v: str) -> None:
    """Windows VERSIONINFO resource in PyInstaller's version-file format."""
    a, b, c = (int(x) for x in v.split("."))
    text = f"""# UTF-8 -- generated by build.py, do not edit
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, 0),
    prodvers=({a}, {b}, {c}, 0),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'AEYE'),
      StringStruct('FileDescription', 'AEYE -- the all-seeing local LLM container'),
      StringStruct('FileVersion', '{a}.{b}.{c}.0'),
      StringStruct('InternalName', 'AEYE'),
      StringStruct('LegalCopyright', 'AEYE'),
      StringStruct('OriginalFilename', 'AEYE.exe'),
      StringStruct('ProductName', 'AEYE'),
      StringStruct('ProductVersion', '{a}.{b}.{c}.0')
    ])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    os.makedirs(ASSETS, exist_ok=True)
    with open(os.path.join(ASSETS, "version_info.txt"), "w", encoding="utf-8") as f:
        f.write(text)


def generate_skull_frames() -> None:
    """Port of static/skull.js's mandible drop: build 3 full-skull frames
    (jaw closed / ajar / open) for the installer's animated speaking skull."""
    JAW_AT, DROP = 20, 2
    MOUTH = {0: (20, 35), 1: (19, 35), 2: (19, 36)}
    try:
        with open(os.path.join(ROOT, "skull.txt"), encoding="utf-8") as f:
            text = f.read()
    except OSError:
        print("  [i] skull.txt missing -- skipping frame generation")
        return
    lines = text.replace("\r", "").rstrip().split("\n")
    if len(lines) <= JAW_AT:
        print("  [i] skull.txt too short -- skipping frame generation")
        return
    W = max(len(l) for l in lines)
    cranium = lines[:JAW_AT]
    lower = [list(l.ljust(W)) for l in lines[JAW_AT:]]
    statics = [[" "] * W for _ in range(len(lower) + DROP)]
    jaw = []
    for r, cells in enumerate(lower):
        m = MOUTH.get(r)
        for c, ch in enumerate(cells):
            if ch == " ":
                continue
            if m and m[0] <= c < m[1]:
                statics[r][c] = ch
            else:
                jaw.append((r, c, ch))
    out = os.path.join(ASSETS, "skull_frames")
    os.makedirs(out, exist_ok=True)
    for k in range(DROP + 1):
        g = [row[:] for row in statics]
        for (r, c, ch) in jaw:
            g[r + k][c] = ch
        frame = "\n".join(cranium) + "\n" + "\n".join("".join(row) for row in g)
        with open(os.path.join(out, f"jaw{k}.txt"), "w", encoding="utf-8") as f:
            f.write(frame)
    print(f"  [OK] wrote {DROP + 1} skull frames to {out}")


def copy_icon() -> None:
    """The installer's SetupIconFile points at assets\\AEYE.ico; the source of
    truth is the repo-root AEYE.ico. Keep assets\\ in sync each build."""
    src = os.path.join(ROOT, "AEYE.ico")
    if os.path.exists(src):
        os.makedirs(ASSETS, exist_ok=True)
        shutil.copy2(src, os.path.join(ASSETS, "AEYE.ico"))
        print("  [OK] AEYE.ico copied to assets/")
    else:
        print("  [i] AEYE.ico not found at repo root -- installer icon skipped")


def fetch_webview2() -> None:
    if os.path.exists(WEBVIEW2_EXE):
        print("  [OK] WebView2 bootstrapper already present")
        return
    os.makedirs(ASSETS, exist_ok=True)
    print(f"  downloading WebView2 bootstrapper -> {WEBVIEW2_EXE}")
    try:
        urllib.request.urlretrieve(WEBVIEW2_URL, WEBVIEW2_EXE)
        print("  [OK] WebView2 bootstrapper fetched")
    except Exception as e:
        print(f"  [i] could not fetch WebView2 bootstrapper ({e}).")
        print("      The installer will still build; it just won't auto-install")
        print("      WebView2 offline. Drop the file at assets\\ to enable it.")


def fetch_default_voice() -> None:
    """Pre-fetch the default Piper voice into assets/hf-cache so the installer
    can seed it and TTS works offline out of the box."""
    try:
        from huggingface_hub import hf_hub_download
    except ImportError:
        print("  [i] huggingface_hub not in the build env -- skipping voice "
              "pre-fetch (voices will download on first use).")
        return
    cache = os.path.join(ASSETS, "hf-cache")
    os.makedirs(cache, exist_ok=True)
    os.environ["HF_HOME"] = cache
    onnx = f"{DEFAULT_VOICE_DIR}/{DEFAULT_VOICE_KEY}.onnx"
    try:
        for rel in (onnx, onnx + ".json"):
            hf_hub_download(PIPER_REPO, rel)
        print(f"  [OK] default voice ({DEFAULT_VOICE_KEY}) cached in {cache}")
    except Exception as e:
        print(f"  [i] voice pre-fetch failed ({e}) -- will download on demand.")


# --- external tools --------------------------------------------------------
def find_iscc() -> str:
    cands = [shutil.which("iscc"), shutil.which("ISCC")]
    for ver in ("7", "6"):
        for pf in (r"C:\Program Files", r"C:\Program Files (x86)"):
            cands.append(os.path.join(pf, f"Inno Setup {ver}", "ISCC.exe"))
    for c in cands:
        if c and os.path.exists(c):
            return c
    return ""


def clean() -> None:
    for d in (BUILD, DIST):
        if os.path.isdir(d):
            shutil.rmtree(d, ignore_errors=True)
    print("  [OK] cleaned build/ and dist/")


# --------------------------------------------------------------------------
def main() -> None:
    ap = argparse.ArgumentParser(description="Build the AEYE installer.")
    ap.add_argument("--bump", choices=("major", "minor", "patch"))
    ap.add_argument("--set", dest="setver", help="set an explicit X.Y.Z version")
    ap.add_argument("--no-installer", action="store_true", help="freeze only")
    ap.add_argument("--no-voice", action="store_true",
                    help="skip pre-fetching the default Piper voice")
    args = ap.parse_args()

    # 1. version
    version = read_version()
    if args.setver:
        version = args.setver
    elif args.bump:
        version = bump(version, args.bump)
    if version != read_version():
        write_version(version)
    log(f"Building AEYE v{version}")

    # 2. clean
    log("Cleaning")
    clean()

    # 3. generate build inputs
    log("Generating build inputs")
    pyver = write_pybuild()
    print(f"  [OK] build Python {pyver} recorded (pybuild.txt)")
    write_version_info(version)
    print("  [OK] version resource written (assets/version_info.txt)")
    generate_skull_frames()
    copy_icon()
    fetch_webview2()
    if not args.no_voice:
        fetch_default_voice()

    # 4. PyInstaller (use the running interpreter so ABI matches pybuild.txt)
    log("Freezing with PyInstaller")
    run([sys.executable, "-m", "PyInstaller", "--noconfirm", "aeye.spec"])
    app_dir = os.path.join(DIST, "AEYE")
    if not os.path.isdir(app_dir):
        sys.exit("[X] PyInstaller did not produce dist/AEYE -- aborting.")
    print(f"  [OK] frozen app at {app_dir}")

    # 5. Inno Setup
    if args.no_installer:
        log("Skipping installer (--no-installer)")
        return
    iscc = find_iscc()
    if not iscc:
        sys.exit("[X] ISCC.exe (Inno Setup 6.1+) not found. Install Inno Setup, "
                 "or re-run with --no-installer.")
    log("Building installer with Inno Setup")
    run([iscc, f"/DAppVersion={version}", f"/DAppSrc={app_dir}",
         os.path.join("installer", "aeye.iss")])

    out = os.path.join(DIST, f"aeye-setup-v{version}.exe")
    if os.path.exists(out):
        mb = os.path.getsize(out) / 2**20
        log("Done")
        print(f"  [OK] {out}  ({mb:.1f} MB)")
    else:
        sys.exit("[X] Installer build finished but the expected output is missing.")


if __name__ == "__main__":
    main()
